version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Устанавливаем переменные окружения, если ваше Django приложение их использует
      DATABASE_NAME: ospan
      DATABASE_USER: ospan
      DATABASE_PASSWORD: ospan
      DATABASE_HOST: 185.129.49.37
      DATABASE_PORT: 3306
    volumes:
      - .:/user/src/e-book
    command: python manage.py runserver 0.0.0.0:8000
